Repository dhlab-basel/Salsah, pull requests merged in 2018-05, with the labels that each got.

#218 Set list edit according to user permissions (only admins can edit)
  src/app/view/dashboard/user/user-profile/user-profile.component.ts
  src/app/view/modules/listing/lists-list/lists-list.component.html
  src/app/view/modules/listing/lists-list/lists-list.component.scss
  src/app/view/modules/listing/lists-list/lists-list.component.ts
Labels: enhancement, in progress

#245 Entity Iris are now objects in JSON-LD
  src/app/model/services/ontologycache.service.ts
  src/app/model/test-data/ontologycache/beol-complex-onto.json
  src/app/model/test-data/ontologycache/knora-api-complex-onto.json
  src/app/model/webapi/knora/v2/convert-jsonld.ts
  src/app/view/properties/still-image-osdviewer/still-image-osdviewer.component.spec.ts
Labels: needs-coordination-with-webapi

#247 More testing for JSON-LD
  src/app/model/services/ontologycache.service.spec.ts
  src/app/model/test-data/resources/BookWithIncomingPages.json
  src/app/model/test-data/resources/BookWithIncomingPages2.json
  src/app/model/test-data/resources/EulerLetter_176-O.json
  src/app/model/test-data/resources/SearchResultEuler.json
  src/app/model/test-data/resources/Testthing.json
  src/app/model/webapi/knora/v2/convert-jsonld.spec.ts
  src/app/model/webapi/knora/v2/convert-jsonld.ts
Labels: enhancement

#254 build (travis): add prod build
  .travis.yml
  fixes/jdnconvertiblecalendardateadapter/index.d.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/view/modules/form/file-uploader/file-uploader.component.html
  src/app/view/modules/form/file-uploader/file-uploader.component.scss
  src/app/view/modules/form/file-uploader/file-uploader.component.spec.ts
  src/app/view/modules/form/file-uploader/file-uploader.component.ts
Labels: enhancement

#255 fix (beol prefix)
  src/app/model/services/beol.service.ts
Labels: bug

#256 Update change password
  src/app/view/modules/form/user-form/user-password/user-password.component.html
  src/app/view/modules/form/user-form/user-password/user-password.component.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
Labels: enhancement

#252 Accept Knora API graph responses
  src/app/app.config.ts
  src/app/model/services/ontology.service.ts
  src/app/model/services/ontologycache.service.spec.ts
  src/app/model/services/ontologycache.service.ts
  src/app/model/services/resource.service.ts
  src/app/model/test-data/ontologycache/anything-complex-onto.json
  src/app/model/test-data/ontologycache/beol-complex-onto.json
  src/app/model/test-data/ontologycache/knora-api-complex-onto.json
  src/app/model/test-data/ontologycache/ontology-metadata.json
  src/app/model/test-data/ontologycache/something-complex-onto.json
  src/app/model/test-data/resources/BookWithIncomingPages.json
  src/app/model/test-data/resources/BookWithIncomingPages2.json
  src/app/model/test-data/resources/EulerLetter_176-O.json
  src/app/model/test-data/resources/SearchForHolzschnitt.json
  src/app/model/test-data/resources/SearchResultEuler.json
  src/app/model/test-data/resources/SearchResultNarr.json
  src/app/model/test-data/resources/Testthing.json
  src/app/model/test-data/resources/emptyResponse.json
  src/app/model/webapi/knora/v2/convert-jsonld.spec.ts
  src/app/model/webapi/knora/v2/convert-jsonld.ts
  src/app/utils.spec.ts
  src/app/view/modules/object/resource-object/resource-object.component.ts
  src/app/view/modules/search/extended-search/extended-search.component.spec.ts
  src/app/view/properties/still-image-osdviewer/still-image-osdviewer.component.spec.ts
Labels: enhancement
