Repository dhlab-basel/Salsah, pull requests merged in 2018-03, with the labels that each got.

#169 feature (list value): display name of the list node
  src/app/app.config.ts
  src/app/model/webapi/knora/v2/convert-jsonld.ts
  src/app/model/webapi/knora/v2/read-property-item.ts
Labels: enhancement

#190 reafctor (ontology cache): adapt ontology cache service
  src/app/app.config.ts
  src/app/model/services/ontologycache.service.spec.ts
  src/app/model/services/ontologycache.service.ts
  src/app/model/test-data/ontologycache/beol-complex-onto.json
  src/app/model/test-data/ontologycache/knora-api-complex-onto.json
  src/app/view/modules/search/extended-search/extended-search.component.spec.ts
Labels: enhancement

#193 feature (mathjax directive): scroll to target
  src/app/app.config.ts
  src/app/view/modules/other/mathjax.directive.ts
  src/app/view/templates/beol/beol.component.ts
Labels: enhancement

#204 refactor (update version of jdnconvertibledateadapter)
  package.json
  yarn.lock
Labels: bug

#207 fix (salsah): remove hardcoded ontology iris
  src/app/model/services/beol.service.ts
  src/app/model/services/ontologycache.service.spec.ts
  src/app/view/dashboard/dashboard.component.html
  src/app/view/dashboard/dashboard.component.ts
  src/app/view/modules/search/extended-search/extended-search.component.spec.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: bug

#206 Fix Persons' Names on BEOL landing Page
  src/app/view/templates/beol/beol.component.ts
Labels: bug, enhancement

#212 Fixes for build in production mode
  package.json
  src/app/model/services/beol.service.ts
  src/app/model/webapi/knora/v2/read-property-item.ts
  src/app/view/modules/search/extended-search/select-property/specify-property-value/specify-property-value.component.ts
  src/environments/environment.integration.ts
  src/environments/environment.mock.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  yarn.lock
Labels: bug

#215 Adaptions for Changes in Knora-API
  src/app/app.config.ts
  src/app/model/services/incoming.service.ts
  src/app/model/services/knarqlgeneration.service.ts
  src/app/model/services/ontologycache.service.spec.ts
  src/app/model/services/ontologycache.service.ts
  src/app/model/test-data/ontologycache/beol-complex-onto.json
  src/app/model/test-data/ontologycache/knora-api-complex-onto.json
  src/app/model/webapi/knora/v2/convert-jsonld.ts
Labels: needs-coordination-with-webapi

#185 CREATE new list
  src/app/app.module.ts
  src/app/model/services/lists.service.ts
  src/app/view/modules/dialog/form-dialog/form-dialog.component.html
  src/app/view/modules/form/edit-list-info/edit-list-info.component.html
  src/app/view/modules/form/edit-list-info/edit-list-info.component.scss
  src/app/view/modules/form/edit-list-info/edit-list-info.component.spec.ts
  src/app/view/modules/form/edit-list-info/edit-list-info.component.ts
  src/app/view/modules/form/edit-node-info/edit-node-info.component.html
  src/app/view/modules/form/edit-node-info/edit-node-info.component.ts
  src/app/view/modules/form/list-form/list-form.component.html
  src/app/view/modules/form/list-form/list-form.component.scss
  src/app/view/modules/form/list-form/list-form.component.spec.ts
  src/app/view/modules/form/list-form/list-form.component.ts
  src/app/view/modules/framework/framework-for-listings/framework-for-listings.component.html
  src/app/view/modules/framework/framework-for-listings/framework-for-listings.component.ts
  src/app/view/modules/listing/lists-list/lists-list.component.html
  src/app/view/modules/listing/lists-list/lists-list.component.ts
Labels: in progress
